version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: gizilo/backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgres
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    restart: always
    
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=gizilodb
      - POSTGRES_USER=gizilo
      - POSTGRES_PASSWORD=gizilo890
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres-data:
